### ISSUE TITLE
V.0.4.0 Still has the Lexer issue 😕

### ISSUE THREAD

**Issue by Moosems** [rdbende/chlorophyll#43]
```python
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/DIP-dev/DIP.py", line 12, in <module>
    from DIP_module.editor import Editor
  File "/Users/Moosems/Desktop/DIP-dev/DIP_module/editor.py", line 9, in <module>
    from chlorophyll import CodeView
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chlorophyll/__init__.py", line 1, in <module>
    from .codeview import CodeView
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chlorophyll/codeview.py", line 20, in <module>
    LexerType = Union[Type[pygments.lexer.Lexer], pygments.lexer.Lexer]
                           ^^^^^^^^^^^^^^
AttributeError: module 'pygments' has no attribute 'lexer'. Did you mean: 'lexers'?
```

**Comment by Moosems** [comment]
```
Requirement already satisfied: pygments in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from chlorophyll) (2.12.0)
```

**Comment by Moosems** [comment]
I upgraded pygments and got the same issue.

**Comment by rdbende** [comment]
Yup, I checked it out, and it doesn't seem to be a new thing. It work for me though.

**Comment by Moosems** [comment]
Really? When I try to see the Lexer class in VS Code it also acts like it doesn't exist.

**Comment by Moosems** [comment]
Note that it wants `lexers` (what we had before) instead of `lexer`.

**Comment by Moosems** [comment]
Gonna get breakfast quickly, will send a video of my end :).

**Comment by Moosems** [comment]
https://github.com/rdbende/chlorophyll/assets/95927277/262fe2ba-8ba9-4bd0-a1e7-ffc694421e92

@rdbende

**Comment by Moosems** [comment]
That fixes it.

**Comment by rdbende** [comment]
https://pypi.org/project/chlorophyll/0.4.1/
